[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
essential-constraint-asm = { path = "crates/constraint-asm" }
essential-state-asm = { path = "crates/state-asm" }
essential-types = { path = "crates/types" }
hex = "0.4.3"
postcard = { version = "1.0.8", features = [ "alloc" ] }
sha2 = "0.10.8"
serde = { version = "1.0.195", features = ["derive"], default-features = false }
serde_json = "1.0.111"
tempfile = "3.9.0"
