[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
essential-constraint-asm = { path = "crates/constraint-asm" }
essential-state-asm = { path = "crates/state-asm" }
essential-types = { path = "crates/types" }
hex = "0.4.3"
serde = { version = "1.0.195", features = ["derive"] }
tempfile = "3.9.0"
