[package]
edition.workspace = true
name = "ui"
version = "0.1.0"

[dependencies]
eframe = "0.26"
egui = "0.26.0"
hex.workspace = true
intent-server.workspace = true
essential_types.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
yurtc.workspace = true
