[package]
name = "essential-asm-gen"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
serde.workspace = true
serde_yaml = "0.9"
syn = { version = "2", features = ["extra-traits", "full", "printing"] }
