[package]
name = "essential-asm-gen"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
essential-asm-spec.workspace = true
essential-types.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
