[package]
edition = "2021"
name = "test_state_read"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guest_sdk = { path = "../../crates/guest" }

[lib]
crate-type = ["cdylib", "rlib"]
name = "test_state_read"
