[package]
name = "essential-check"
description = "Core logic related to validating Essential state transitions."
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1"
essential-constraint-vm = { workspace = true }
essential-state-read-vm = { workspace = true }
essential-types = { workspace = true }
rayon = { workspace = true }
thiserror = "1"
tokio = { workspace = true }
