[package]
name = "guest_sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "guest_sdk"
crate-type = [ "cdylib", "rlib" ]