[package]
name = "intent-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
bitvec = "1.0.1"
wasmtime = "16.0.0"

# TODO: Choose or build a better bytecode encoding
serde = "1.0.195"
serde_json = "1.0.111"