name: ci
run-name: CI

on: [push]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    env:
        CARGO_NET_GIT_FETCH_WITH_CLI: 'true'
    steps:
      - name: Provide Access to Private Repos
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}
              ${{ secrets.SSH_PRIVATE_KEY_SELF }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - run: cargo fmt --check
